require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ForecastsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Forecast. As you add validations to Forecast, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForecastsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all forecasts as @forecasts" do
      forecast = Forecast.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:forecasts)).to eq([forecast])
    end
  end

  describe "GET #show" do
    it "assigns the requested forecast as @forecast" do
      forecast = Forecast.create! valid_attributes
      get :show, {:id => forecast.to_param}, valid_session
      expect(assigns(:forecast)).to eq(forecast)
    end
  end

  describe "GET #new" do
    it "assigns a new forecast as @forecast" do
      get :new, {}, valid_session
      expect(assigns(:forecast)).to be_a_new(Forecast)
    end
  end

  describe "GET #edit" do
    it "assigns the requested forecast as @forecast" do
      forecast = Forecast.create! valid_attributes
      get :edit, {:id => forecast.to_param}, valid_session
      expect(assigns(:forecast)).to eq(forecast)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Forecast" do
        expect {
          post :create, {:forecast => valid_attributes}, valid_session
        }.to change(Forecast, :count).by(1)
      end

      it "assigns a newly created forecast as @forecast" do
        post :create, {:forecast => valid_attributes}, valid_session
        expect(assigns(:forecast)).to be_a(Forecast)
        expect(assigns(:forecast)).to be_persisted
      end

      it "redirects to the created forecast" do
        post :create, {:forecast => valid_attributes}, valid_session
        expect(response).to redirect_to(Forecast.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved forecast as @forecast" do
        post :create, {:forecast => invalid_attributes}, valid_session
        expect(assigns(:forecast)).to be_a_new(Forecast)
      end

      it "re-renders the 'new' template" do
        post :create, {:forecast => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested forecast" do
        forecast = Forecast.create! valid_attributes
        put :update, {:id => forecast.to_param, :forecast => new_attributes}, valid_session
        forecast.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested forecast as @forecast" do
        forecast = Forecast.create! valid_attributes
        put :update, {:id => forecast.to_param, :forecast => valid_attributes}, valid_session
        expect(assigns(:forecast)).to eq(forecast)
      end

      it "redirects to the forecast" do
        forecast = Forecast.create! valid_attributes
        put :update, {:id => forecast.to_param, :forecast => valid_attributes}, valid_session
        expect(response).to redirect_to(forecast)
      end
    end

    context "with invalid params" do
      it "assigns the forecast as @forecast" do
        forecast = Forecast.create! valid_attributes
        put :update, {:id => forecast.to_param, :forecast => invalid_attributes}, valid_session
        expect(assigns(:forecast)).to eq(forecast)
      end

      it "re-renders the 'edit' template" do
        forecast = Forecast.create! valid_attributes
        put :update, {:id => forecast.to_param, :forecast => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested forecast" do
      forecast = Forecast.create! valid_attributes
      expect {
        delete :destroy, {:id => forecast.to_param}, valid_session
      }.to change(Forecast, :count).by(-1)
    end

    it "redirects to the forecasts list" do
      forecast = Forecast.create! valid_attributes
      delete :destroy, {:id => forecast.to_param}, valid_session
      expect(response).to redirect_to(forecasts_url)
    end
  end

end
